### ISSUE TITLE
在尝试读取来自外接摄像头MJPEG格式的数据时报 imdecode错误. imdecode error when dealing with MJPEG data

### ISSUE THREAD

**Issue by sjiang95** [xxradon/libv4l2_opencv_mat#2]
`terminate called after throwing an instance of 'cv::Exception'`
`what():  OpenCV(4.5.0-dev) /home/jiang/opencv_build/opencv/modules/imgcodecs/src/loadsave.cpp:770: error: (-215:Assertion failed) buf.checkVector(1, CV_8U) > 0 in function 'imdecode_'`

是否可能是`src/V4l2Capture.cpp`中`readImage = cv::imdecode(v4l2Mat, 1 );`所导致的错误呢？
Is there a possibility that line `readImage = cv::imdecode(v4l2Mat, 1 );` in `src/V4l2Capture.cpp`causes this problem?

**Comment by jiangdayu555** [comment]
the same question ,why

**Comment by Mediumcore** [comment]
the same question ,why
